### ISSUE TITLE
foto

### ISSUE THREAD

**Issue by Miranda-03** [pdepjm/2024-tp0-presentacion-Damian-Mz#1]
pone foto

acá te dejo una si no tenes: 
![image](https://github.com/pdepjm/2024-tp0-presentacion-Damian-Mz/assets/72475370/774d655c-7fa5-4575-b6ec-ddbe0596fd34)

**Comment by DamianMarzocca** [comment]
Muchas gracias por la recomendación de foto, voy a agregar una. Desgraciadamente la menta granizada no es de mi gusto, por lo que voy a agregar una foto mía.
