### ISSUE TITLE
No me gusto cierto aspecto

### ISSUE THREAD

**Issue by NicolasSchkurko** [pdepjm/2024-tp0-presentacion-Damian-Mz#2]
Buenas noches estimado. En el respectivo Readme falto aclarar la adiccion al truco que compartimos junto a nuestros dos restantes compañeros.

**Comment by Damian-Mz** [comment]
Muchísimas gracias por recordarme

**Comment by DamianMarzocca** [comment]
Muchísimas gracias por recordarme
